name: gbscout
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - scouting-shared
    env_file:
      - ../../../.public.env
      - ../../../.secret.env
    environment:
      - BACKEND_PROXY_URL=http://backend:4590
    ports:
      - "${FRONTEND_PORT}:443" # Maps host:${FRONTEND_PORT} to container:443
networks:
  scouting-shared:
    external: true
    name: scouting-network
